[versions]
# Plugins
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"
dagger = "2.57.2"
daggerCompiler = "2.57.2"
hiltAndroidCompiler = "2.57.2"
hiltCompiler = "2.57.2"
hiltCompilerVersion = "1.3.0"
hiltNavigationCompose = "1.3.0"

#UI
material3 = "1.4.0"
material3AdaptiveNavigationSuite = "1.5.0-alpha08"
material3WindowSizeClass = "1.4.0"
swiperefresh = "0.36.0"
plugin-compose = "1.9.3"
constraintlayoutComposeVersion = "1.1.1"
composeBom = "2025.11.00"


agp = "8.13.0"
kotlin = "2.2.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
navigation = "2.9.6"
cameraLifecycle = "1.5.1"
cameraView = "1.5.1"

# Libraries
room = "2.8.3"
sqlite = "2.6.1"
gson = "2.13.2"
converterGson = "3.0.0"

#Network
retrofit = "3.0.0"
loggingInterceptor = "5.3.0"

zxingAndroidEmbedded = "4.3.0"
animation = "1.9.4"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompilerVersion" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutComposeVersion" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "swiperefresh" }

material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
androidx-material3-adaptive-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite", version.ref = "material3AdaptiveNavigationSuite" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2" }
androidx-camera-core = { module = "androidx.camera:camera-core" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
room-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }


retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltCompiler" }

androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-core = { id = "org.jetbrains.compose", version.ref = "plugin-compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id ="com.google.devtools.ksp", version = "2.2.10-2.0.2" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerCompiler" }