[versions]
agp = "8.3.0"
annotation = "1.7.1"
circleimageview = "3.1.0"
constraintlayout = "2.1.4"
googleServices = "4.4.1"
junit = "4.13.2"
junitJunitVersion = "4.12"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
legacySupportV4 = "1.0.0"
lifecycleLivedataKtx = "2.7.0"
material = "1.11.0"
places = "3.3.0"
navigationFragment = "2.7.7"
retrofit = "2.9.0"
threetenabp = "1.4.4"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-junit-v412 = { module = "junit:junit", version.ref = "junitJunitVersion" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

